---
apiVersion: v1
kind: Namespace
metadata:
  name: foo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: foo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: patrikkj/nginx:v0.2.0
          ports:
            - containerPort: 80
